name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  publish-code-coverage:
    if: ${{ !contains(github.event.head_commit.message, 'coverage skip') }}
    runs-on: ubuntu-latest
    env:
      JDK_VERSION:  ${{ matrix.jdk }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate Coverage Report
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --configuration-cache jacocoMergedReport --no-build-cache

      - name: Publish Coverage
        if: success()
        uses: codecov/codecov-action@v2
