name: Pre Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  gradle:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [8, 11, 17]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION:  ${{ matrix.jdk }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'adopt'
    - name: Build detekt
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build -x detekt
    - uses: actions/upload-artifact@v2
      with:
        name: heap-dump
        path: '**.hprof'
        if-no-files-found: ignore
    - name: Run detekt-cli --help
      run: ./gradlew :detekt-cli:runWithHelpFlag
    - name: Run detekt-cli with argsfile
      run: ./gradlew :detekt-cli:runWithArgsFile

  verify-generated-config-file:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Verify Generated Detekt Config File
      uses: gradle/gradle-build-action@v2
      with:
        arguments: verifyGeneratorOutput

  compile-test-snippets:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Build and compile test snippets
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test -x ":detekt-gradle-plugin:test" -Pcompile-test-snippets=true
